# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: deps
      prefix-development: "deps(dev)"
    ignore:
      - dependency-name: "@angular/common"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@angular/animations"
      - dependency-name: "@angular/cli"
      - dependency-name: "@angular/compiler"
      - dependency-name: "@angular/compiler-cli"
      - dependency-name: "@angular/core"
      - dependency-name: "@angular/forms"
      - dependency-name: "@angular/platform-browser"
      - dependency-name: "@angular/platform-browser-dynamic"
      - dependency-name: "ng-packagr"
      - dependency-name: "typescript"
      - dependency-name: "zone.js"
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: deps
      prefix-development: "deps(dev)"
