tsconfig: ./projects/ngforage/tsconfig.lib.json
output: ./dist/demo/docs
name: NgForage API docs
theme: material
hideGenerator: true
disablePrivate: true
disableInternal: true
customFavicon: demo/favicon.ico
disableCoverage: true

