branch: master
tagFormat: '${version}'

verifyConditions:
- path: &npm '@semantic-release/npm'
  pkgRoot: '.'
- &gh '@semantic-release/github'

prepare:
- '@semantic-release/changelog'
- *npm
- path: &exec '@semantic-release/exec'
  cmd: npm run sync
- path: *exec
  cmd: npm run build:lib
- path: '@semantic-release/git'
  message: 'chore(release): ${nextRelease.version}'
  assets:
  - CHANGELOG.md
  - README.md
  - MIGRATING.md
  - package.json
  - package-lock.json
  - projects/ngforage/package.json

publish:
- path: *exec
  cmd: bash -c "cd dist/ngforage && npm publish"
- *gh

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
