sudo: false
language: node_js
node_js: lts/*

os:
- osx
- linux

before_cache: rm -rf ./node_modules/.cache
cache:
  yarn: true
  directories:
  - node_modules

before_install:
- npm i -g greenkeeper-lockfile yarn
- greenkeeper-lockfile-update

install:
- &yInstall yarn install --check-files
- yarn run sync
- *yInstall

script: yarn run lint && yarn run test && yarn run build:demo:prod

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

stages:
- Test
- Release

jobs:
  include:
  - stage: Test
    os: osx
    sudo: required
    addons:
      apt:
        packages:
        - xvfb
    before_script:
    - "export DISPLAY=:99.0"
    - sudo Xvfb :99 -ac -screen 0 1024x768x8 &
    - sleep 3
    script: yarn run test --browsers Safari
  - stage: Test
    os: linux
    addons:
      chrome: stable
      firefox: latest
