language: node_js
node_js: lts/*

env:
  global:
    - GK_LOCK_YARN_OPTS=-W

cache:
  yarn: true

before_install:
  - npm i -g yarn greenkeeper-lockfile
  - greenkeeper-lockfile-update

install:
  - yarn install --check-files
  - yarn run sync

script:
  - yarn run lint
  - yarn test
  - yarn run build:demo --aot
  - yarn run build:lib
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

stages:
  - Test
  - name: Release
    if: branch = master AND type = push

jobs:
  include:
    - stage: Test
      os: linux
      addons:
        chrome: stable
        firefox: latest
    #   - stage: Test
    #     os: osx
    #     sudo: required
    #     addons:
    #       apt:
    #         packages:
    #         - xvfb
    #     before_script:
    #     - "export DISPLAY=:99.0"
    #     - sudo Xvfb :99 -ac -screen 0 1024x768x8 &
    #     - sleep 3
    #     script: yarn run test --browsers Safari
    - stage: Release
      before_install: npm i -g yarn
      before_script: yarn run build:lib
      script: semantic-release
      after_success: []
      after_script: []
      before_deploy:
        - yarn run build:demo:prod
        - yarn run compodoc
      deploy:
        - provider: pages
          skip_cleanup: true
          on:
            tags: true
          local_dir: dist/demo
          target_branch: gh-pages
          github_token: $GH_TOKEN
