sudo: false
language: node_js
node_js: stable
group: travis_latest

stages:
  - &std_stage_name Test & Lint
  - name: Deploy
    if: tag IS present

cache:
  directories:
    - node_modules

std_job: &std_job
  stage: *std_stage_name
  before_cache: rm -rf node_modules/.cache
  os: linux
  addons: &browsers
    chrome: stable
    firefox: latest
  after_success: cat ./coverage/lcov.info | coveralls
  before_install:
    - npm install -g greenkeeper-lockfile
    - greenkeeper-lockfile-update
  after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
  script:
    - gulp tslint
    - npm test
    - gulp build:demo:prod

jobs:
  include:
    - <<: *std_job
    - <<: *std_job
      os: osx
      osx_image: xcode9.2
      sudo: required
      addons:
        apt:
          packages:
            - xvfb
      before_script:
        - "export DISPLAY=:99.0"
        - sudo Xvfb :99 -ac -screen 0 1024x768x8 &
        - sleep 3
      script: npm test -- --browsers Safari
    - stage: Deploy
      before_script:
        - gulp package build:demo:prod
        - openssl aes-256-cbc -K $encrypted_1d92b726f585_key -iv $encrypted_1d92b726f585_iv -in .npmrc.enc -out ~/.npmrc -d
      script: npm publish ./dist
      deploy:
        - provider: pages
          skip_cleanup: true
          on:
            tags: true
          local_dir: ./demo
          target_branch: gh-pages
          github_token: $GH_TOKEN
        - provider: releases
          skip_cleanup: true
          api_key: $GH_TOKEN
          file: dist.tgz
          on:
            tags: true

