sudo: false
language: node_js
node_js: 9

env:
  - CI_NG_VERSION=4
  - CI_NG_VERSION=5
    CI_PUBLISH=1
    CI_LINT=1

cache:
  directories:
    - node_modules

before_install: node ./ci/TravisMgr.js backup-pkg set-version

script:
  - bash -c 'if [ "$CI_LINT" = "1" ]; then npm run tslint; fi;'
  - bash -c 'if [ "$CI_PUBLISH" = "1" ]; then npm run build:demo:aot:prod; else npm run build:demo:aot; fi;'
  - npm run build
  - npm test

after_script: node ./ci/TravisMgr.js restore-pkg

after_success: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

before_cache: rm -rf ./node_modules/puppeteer

deploy:
  - provider: npm
    skip_cleanup: true
    email: a.molcanovas@gmail.com
    on:
      tags: true
      condition: $CI_PUBLISH = "1"
    api_key:
      secure: W46BFHze4FhyerHUQRzn7KI/wdTQGEu7B6y9zE4HP/n2+Ws18uE1x6Io0IV4AVSFaeIWLYqsv5fb7U43WNkC4i3ylGU/aNkAIigtIwyGbTPxWuyRtTN5YPa/djN5iRSNA2VBa5XnUq4FziGDbfHYIAV+L81Ld9HNSjyAqzX21mdJw6mR5Nktkv1+bfLhTpUMifat1xZqX1HsK45oVZFIFumAZKgOOgEpdUsLQT57NhcSoUx6QarhscO5hs3VywLjmIgrvyP2jX0HyAX/xkTP33vwhWvwSm5swlg7tbfC4T+00RDiabknDQsx6FAXpHQ158rJaQ8vzfbVgDyWEQYTKnArG+pikSjzqCZBx5BBwo9UFsuQW6HsoyB/vheJHyHHRIn62aAS/WUvE70Yn0lDXpmbLnc4+jcQteOwyyQ49dzP2/9/cAIc8gi/dMRlIvguC++bEuTRi0jDeIbIBmmP9J6EA/upfGPEOB/b1w1aZlvWnrb1cSX6Y6aqM2FupVKqIlKUcPeHf1wPOofdYY6hDTyB8lUTOsdYzZI+4mjVxJIhL5xDvq7pDxHTQdR5hTdYpuJQ01cFpnGr84CTgta3Ou9L/eU9XC3ritFHhvcWsWenpySug6ZMmIRFeEJdIZhFIwtGofLavHvJSKETdmzGUsHfK34T/umz5JQRfvMbdSU=
  - provider: pages
    skip_cleanup: true
    on:
      tags: true
      condition: $CI_PUBLISH = "1"
    local_dir: ./.demo
    target_branch: gh-pages
    github_token:
      secure: Kju931qQisMcypiCKDju8dSHufONW0+/OjGoBGBt4LpUKNdOUfA05G87cgftgaVR0qnIbIbTx3fOs5/xPgl0O1wq8h/+ThSUx+KsHWXXAjOVSs3w1/zFtLvywdRf7ag1SiK32/UVSj4bXfHqHzKr4/5V9fvzOcCU9tf2Ogfb8IGIEXQaC7Tpycx0fsz1XypzqpsXCc76IgLYfmcJ28uMcD3mUTNTCwUBvuao4cOJG6KcFNU7v8OswaxnwsJr3ekRaaQ1odFF2zL+Ov1Zl6OsU7r2/BZ9R3L8UFtSdF6Y/pLd9DLCjESkWygDNKn2tkNk6cPi2qeKUWQfzoHweZ2oHpUNYN+dCMYOtOazloQmwrk6BQdkuNppgmrbvrLQUEJOG0XHYcTMuiMuIP43Zlct0DAFAqEC+3BRJfo4IjOAG4AHuXcaAHGiLIsdDu+JwFDET9R+b6WDzzRVmOejq384lLX/eItVmmqnyqmBoIuG19XMeFSGrF2TScn5lLDmM8eNEjp9zHoffmpQV8Ee+WHv85RxeJnO5ajqoQmqXA0aMacvBoov8T6MNyi+udfaRdEZ3AhYwMc9HIdYTjeATR8pnNrgVyTxKxGxhEwabTwUB5hoVy/d3JEwPN2rOvQP+wfxXztOzd+6UigBBTwTMgqNmgnGFzmKV0ThI7YSMCJvC18=
