sudo: false
language: node_js
node_js: 9

env:
  global:
    - secure: "pOa/litDhDy+l1niY4pDtT43bzVlnFL8MppqxyX3nbZ3tmo6hpIuUWDXcS0jT62ut/F2Pj5SUyFGYhe7EiuWlpX7FfhKmkieB6lqtEgW7xIwVnjMIaMXRJxsY62swqDQ+glLsU1X9QnGJDoMMk6L1cqZnu9cZtkdBjqtgygjVxbqv4mVdm4SeFqfmFdm2147t2xrWDvnMiL/ghRp1W7QAwp4QjCAr/22UMTTDTFXT+x+dI6GNhrhiiXPlDGC+tX+ishWqjYBteCWjAOTWZH+QaANDkWaIhZLb8XHuhV11kzJ1oIgrOE7HpiN6QDXbrlNAnZa0uhsHTC7Soet88mHusnfkXt5+m3PIyydRN6dr/mfyIZvE6tZnYM6PBoYDwUOaA97nlG3HhF6BdgI1QONA/R/vIY1qw+7qjOpCxPv2AGkec/6p7vMxWQ9vBatYTzVhs2v1LVQGFb9zI3PXJhzPeY/C3B0I9IejhaibO8zRvg05bVNduvECEyTdfG1wHAWuzsvyIR60dx/X4SZI8/uslZLgq1ZVMrA5gfqW6g8NCW45OqwcbKXP5EH8/Td6Lj7fJWKnqjEI8lDicG0BCEBjzUUyVEwZf+7T2bK1yzsxaIDcvv6GjxjBa6G/qK3xABZYFt7WPoG7m3Ht1RRQ94reRk8kJed5x5IH2tQXlmhmUw="
    - secure: XZ5JBYalDUi5Bz3TUs/SXPgrmUD0OFNQYIk/t1+vkCneUDSfv+tl+dsd7Y1j52NyU1Q+6d41Pg+03ADvLC1YT5YtEV/p5WaxVY70Fj0pnKegS6Wgf6qqPEe8LEa78j6jX7CDN9SJodW6Tt5emWwB32Aw+f814tsDz9kvpNPSByWcbVsix9QvE1uM/DCMxVBbezBZ45PMdI49q/5libk7ioCIGEz0gFaOfAGQ/PHQfqk2Ua+voepLqrbo0asuIlC8EaTJNs07rpwg5lKJW3roaHtMOjKmpChq6cqatfsTUV00rInpp0bhPTkl2cFoXAPPXuKuBre6xjALKJ7bdmurlyG2ovMTUEhvdejW+nDx0/GVLatuZowxAWH/ix2m61BGS/DfSk9Mb2EJrL+4s0r6KO7IZZC4Db3j9zTQKqlLJZCsPwXBw+2f4NYRr9PX9pH9px8UqIaKeNqDu8s6aGoMDWaIQf+4uYkp2sFWS+INQCUHCZNwZ0LBHfYkK8bT4rdWFAGMLYbmSzWvhrWrQ4WVy9QoOxmXu1CZ/GFUZHR4DHnTK8sM6Gb7BK4Y6+0vWcM8vjfLaAZTCtrAyinn8tNuuu4YC2vIUP+Sraqh+k7meX1bD1InbGv54kD8bZKWlOZSuf7t69VYf1TefIBbrTqPJvfs4acF8LPPzFwrOu3igQY=

stages:
  - Lint
  - Test
  - name: Deploy
    if: tag IS present

before_cache: rm -rf ./node_modules/puppeteer
before_script: greenkeeper-lockfile-update

cache:
  directories:
    - node_modules

std_job: &std_job
  stage: Test
  script:
    - npm run build
    - npm run build:demo:aot
    - npm test
  after_script: node ./ci/TravisMgr.js restore-pkg
  after_success: cat ./coverage/lcov.info | coveralls
  before_install: node ./ci/TravisMgr.js backup-pkg set-version

jobs:
  include:
    - stage: Lint
      if: type IN (push, cron)
      script: snyk test --peer
      after_script: greenkeeper-lockfile-upload
      after_success: snyk monitor --peer
    - stage: Lint
      script: npm run tslint
    - <<: *std_job
      env:
        - CI_NG_VERSION=5
    - <<: *std_job
      env:
        - CI_NG_VERSION=4
    - stage: Deploy
      script:
        - npm run build
        - npm run build:demo:aot:prod
      deploy:
        - provider: npm
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          on:
            tags: true
          api_key:
            secure: W46BFHze4FhyerHUQRzn7KI/wdTQGEu7B6y9zE4HP/n2+Ws18uE1x6Io0IV4AVSFaeIWLYqsv5fb7U43WNkC4i3ylGU/aNkAIigtIwyGbTPxWuyRtTN5YPa/djN5iRSNA2VBa5XnUq4FziGDbfHYIAV+L81Ld9HNSjyAqzX21mdJw6mR5Nktkv1+bfLhTpUMifat1xZqX1HsK45oVZFIFumAZKgOOgEpdUsLQT57NhcSoUx6QarhscO5hs3VywLjmIgrvyP2jX0HyAX/xkTP33vwhWvwSm5swlg7tbfC4T+00RDiabknDQsx6FAXpHQ158rJaQ8vzfbVgDyWEQYTKnArG+pikSjzqCZBx5BBwo9UFsuQW6HsoyB/vheJHyHHRIn62aAS/WUvE70Yn0lDXpmbLnc4+jcQteOwyyQ49dzP2/9/cAIc8gi/dMRlIvguC++bEuTRi0jDeIbIBmmP9J6EA/upfGPEOB/b1w1aZlvWnrb1cSX6Y6aqM2FupVKqIlKUcPeHf1wPOofdYY6hDTyB8lUTOsdYzZI+4mjVxJIhL5xDvq7pDxHTQdR5hTdYpuJQ01cFpnGr84CTgta3Ou9L/eU9XC3ritFHhvcWsWenpySug6ZMmIRFeEJdIZhFIwtGofLavHvJSKETdmzGUsHfK34T/umz5JQRfvMbdSU=
        - provider: pages
          skip_cleanup: true
          on:
            tags: true
          local_dir: "./.demo"
          target_branch: gh-pages
          github_token:
            secure: VMkUx7mtTrcVIiI6AjCbVWFFZQ2+W51WoU5cvBHZ4uT84hC5il15QYmfuv752jc2bU8JrTLscqA2e5Twa40XgcaNim5Hh2eLeomHPRRcrfchPg/P41i/Kf63fpIAXFj2Il1zRA4NwtPEkw0mhSIfqdACOCahStutqfTT5ZUgxe5QVUDl/aH+rIqLfS3ZC01hPwKirHRmOZ/l4Whfb9ivaA4aSIEzN3GOO7eR2Tsd7JokyuNrSfoBZFcpJ61X0YP0VaspYVwYt75bp1noTVvx2ItWGVt2qIFiJdIAjlAjfgjkwSXJAawlrIHx5G+ajrlS6nbojmBd4s8UgNeXfIFJAG/AgDUq5uZzdklZmTkX57qrSiU9Uaq+9BYLu8I1ZNJSkieaeAy0PK0+pWBrXGAWd6rZeM5YmrqvVgrJcAST7W6HFYzLoRRmqtki5SysxpXI+ugKQgitGhGq5ES0EnwihXxuQ/xiVEjYLBFG5QviBrUZ3zc7IyfRYwCSNJ546c4XVhkwNkaBBTfz9IN4A7UscibWWd6lbO3w/tQCK+/a4D1IivRV5fnNyLw7BeoTcddWeVNHSRFupL84kE1/0jWrHs8FyMPpYyDO2jyZ9XY14iLiSiaaPIPtRQa4C7g3OEN2Nq2n1iNwmXjb0jQOPBkTBYCFdzkXJcoLagIz51EaHS4=
